-- DROP TABLE llx_scolaris_student
CREATE TABLE llx_scolaris_student (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL DEFAULT 1,
  student_number varchar(32) NOT NULL,
  lastname varchar(128) NOT NULL,
  firstname varchar(128) NOT NULL,
  othernames varchar(128) NULL,
  gender varchar(16) NULL,
  birthdate date NULL,
  birth_place varchar(255) NULL,
  nationality varchar(128) NULL,
  email varchar(255) NULL,
  phone varchar(64) NULL,
  fk_user integer NULL,
  fk_soc integer NULL,
  fk_adherent integer NULL,
  status smallint NOT NULL DEFAULT 1,
  note_private text NULL,
  date_creation datetime NULL,
  tms timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_author integer NULL,
  fk_user_modif integer NULL,
  import_key varchar(14)
) ENGINE=innodb;
