-- DROP TABLE llx_scolaris_bulletin
CREATE TABLE llx_scolaris_bulletin (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL DEFAULT 1,
  fk_student integer NOT NULL,
  fk_enrollment integer NOT NULL,
  fk_semester integer NOT NULL,
  fk_semester_result integer NOT NULL,
  doc_ref varchar(64) NOT NULL,
  version_number integer NOT NULL DEFAULT 1,
  file_name varchar(255) NULL,
  file_path varchar(255) NULL,
  file_hash varchar(128) NULL,
  publication_status varchar(32) NOT NULL DEFAULT 'draft',
  requires_payment tinyint NOT NULL DEFAULT 0,
  amount_ttc decimal(24,8) NOT NULL DEFAULT 0.00000000,
  currency_code varchar(8) NOT NULL DEFAULT 'XOF',
  fk_product integer NULL,
  fk_facture integer NULL,
  payment_status varchar(32) NOT NULL DEFAULT 'not_required',
  generated_at datetime NULL,
  published_at datetime NULL,
  last_download_at datetime NULL,
  download_count integer NOT NULL DEFAULT 0,
  tms timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_generated integer NULL,
  fk_user_published integer NULL,
  import_key varchar(14)
) ENGINE=innodb;
